spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/postgres
    username: BANCA_NOIX_BD
    password: BANCANOIX123
  liquibase:
    change-log: classpath:/config/liquibase/master.xml
  mail:
    hots: smtp.gmail.com
    port: 587
    username: bancanoix@gmail.com
    password: bancanoix123
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          quitwait: false
application:
  email:
    endereco-remetente: bancanoix@gmail.com
    nome-remetente: bancanoix